// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gometheus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveMetricRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	MetricName    string                  `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	MetricType    string                  `protobuf:"bytes,2,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	Delta         *wrapperspb.Int64Value  `protobuf:"bytes,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Value         *wrapperspb.DoubleValue `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMetricRequest) Reset() {
	*x = SaveMetricRequest{}
	mi := &file_gometheus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMetricRequest) ProtoMessage() {}

func (x *SaveMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gometheus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMetricRequest.ProtoReflect.Descriptor instead.
func (*SaveMetricRequest) Descriptor() ([]byte, []int) {
	return file_gometheus_proto_rawDescGZIP(), []int{0}
}

func (x *SaveMetricRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *SaveMetricRequest) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *SaveMetricRequest) GetDelta() *wrapperspb.Int64Value {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *SaveMetricRequest) GetValue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type SaveMetricResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	MetricName    string                  `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	MetricType    string                  `protobuf:"bytes,2,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	Delta         *wrapperspb.Int64Value  `protobuf:"bytes,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Value         *wrapperspb.DoubleValue `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMetricResponse) Reset() {
	*x = SaveMetricResponse{}
	mi := &file_gometheus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMetricResponse) ProtoMessage() {}

func (x *SaveMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gometheus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMetricResponse.ProtoReflect.Descriptor instead.
func (*SaveMetricResponse) Descriptor() ([]byte, []int) {
	return file_gometheus_proto_rawDescGZIP(), []int{1}
}

func (x *SaveMetricResponse) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *SaveMetricResponse) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *SaveMetricResponse) GetDelta() *wrapperspb.Int64Value {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *SaveMetricResponse) GetValue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type SaveMetricsBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*SaveMetricRequest   `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMetricsBatchRequest) Reset() {
	*x = SaveMetricsBatchRequest{}
	mi := &file_gometheus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMetricsBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMetricsBatchRequest) ProtoMessage() {}

func (x *SaveMetricsBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gometheus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMetricsBatchRequest.ProtoReflect.Descriptor instead.
func (*SaveMetricsBatchRequest) Descriptor() ([]byte, []int) {
	return file_gometheus_proto_rawDescGZIP(), []int{2}
}

func (x *SaveMetricsBatchRequest) GetMetrics() []*SaveMetricRequest {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type SaveMetricsBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*SaveMetricResponse  `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMetricsBatchResponse) Reset() {
	*x = SaveMetricsBatchResponse{}
	mi := &file_gometheus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMetricsBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMetricsBatchResponse) ProtoMessage() {}

func (x *SaveMetricsBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gometheus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMetricsBatchResponse.ProtoReflect.Descriptor instead.
func (*SaveMetricsBatchResponse) Descriptor() ([]byte, []int) {
	return file_gometheus_proto_rawDescGZIP(), []int{3}
}

func (x *SaveMetricsBatchResponse) GetMetrics() []*SaveMetricResponse {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type APIError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []string               `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIError) Reset() {
	*x = APIError{}
	mi := &file_gometheus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIError) ProtoMessage() {}

func (x *APIError) ProtoReflect() protoreflect.Message {
	mi := &file_gometheus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIError.ProtoReflect.Descriptor instead.
func (*APIError) Descriptor() ([]byte, []int) {
	return file_gometheus_proto_rawDescGZIP(), []int{4}
}

func (x *APIError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *APIError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *APIError) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_gometheus_proto protoreflect.FileDescriptor

const file_gometheus_proto_rawDesc = "" +
	"\n" +
	"\x0fgometheus.proto\x12\tgometheus\x1a\x1egoogle/protobuf/wrappers.proto\"\xbc\x01\n" +
	"\x11SaveMetricRequest\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x1f\n" +
	"\vmetric_type\x18\x02 \x01(\tR\n" +
	"metricType\x121\n" +
	"\x05delta\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05delta\x122\n" +
	"\x05value\x18\x04 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value\"\xbd\x01\n" +
	"\x12SaveMetricResponse\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x1f\n" +
	"\vmetric_type\x18\x02 \x01(\tR\n" +
	"metricType\x121\n" +
	"\x05delta\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05delta\x122\n" +
	"\x05value\x18\x04 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value\"Q\n" +
	"\x17SaveMetricsBatchRequest\x126\n" +
	"\ametrics\x18\x01 \x03(\v2\x1c.gometheus.SaveMetricRequestR\ametrics\"S\n" +
	"\x18SaveMetricsBatchResponse\x127\n" +
	"\ametrics\x18\x01 \x03(\v2\x1d.gometheus.SaveMetricResponseR\ametrics\"R\n" +
	"\bAPIError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x03(\tR\adetails2\xb3\x01\n" +
	"\x0eMetricsService\x12I\n" +
	"\n" +
	"SaveMetric\x12\x1c.gometheus.SaveMetricRequest\x1a\x1d.gometheus.SaveMetricResponse\x12V\n" +
	"\vSaveMetrics\x12\".gometheus.SaveMetricsBatchRequest\x1a#.gometheus.SaveMetricsBatchResponseB)Z'github.com/m1khalev/gometheus/pkg/protob\x06proto3"

var (
	file_gometheus_proto_rawDescOnce sync.Once
	file_gometheus_proto_rawDescData []byte
)

func file_gometheus_proto_rawDescGZIP() []byte {
	file_gometheus_proto_rawDescOnce.Do(func() {
		file_gometheus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gometheus_proto_rawDesc), len(file_gometheus_proto_rawDesc)))
	})
	return file_gometheus_proto_rawDescData
}

var file_gometheus_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gometheus_proto_goTypes = []any{
	(*SaveMetricRequest)(nil),        // 0: gometheus.SaveMetricRequest
	(*SaveMetricResponse)(nil),       // 1: gometheus.SaveMetricResponse
	(*SaveMetricsBatchRequest)(nil),  // 2: gometheus.SaveMetricsBatchRequest
	(*SaveMetricsBatchResponse)(nil), // 3: gometheus.SaveMetricsBatchResponse
	(*APIError)(nil),                 // 4: gometheus.APIError
	(*wrapperspb.Int64Value)(nil),    // 5: google.protobuf.Int64Value
	(*wrapperspb.DoubleValue)(nil),   // 6: google.protobuf.DoubleValue
}
var file_gometheus_proto_depIdxs = []int32{
	5, // 0: gometheus.SaveMetricRequest.delta:type_name -> google.protobuf.Int64Value
	6, // 1: gometheus.SaveMetricRequest.value:type_name -> google.protobuf.DoubleValue
	5, // 2: gometheus.SaveMetricResponse.delta:type_name -> google.protobuf.Int64Value
	6, // 3: gometheus.SaveMetricResponse.value:type_name -> google.protobuf.DoubleValue
	0, // 4: gometheus.SaveMetricsBatchRequest.metrics:type_name -> gometheus.SaveMetricRequest
	1, // 5: gometheus.SaveMetricsBatchResponse.metrics:type_name -> gometheus.SaveMetricResponse
	0, // 6: gometheus.MetricsService.SaveMetric:input_type -> gometheus.SaveMetricRequest
	2, // 7: gometheus.MetricsService.SaveMetrics:input_type -> gometheus.SaveMetricsBatchRequest
	1, // 8: gometheus.MetricsService.SaveMetric:output_type -> gometheus.SaveMetricResponse
	3, // 9: gometheus.MetricsService.SaveMetrics:output_type -> gometheus.SaveMetricsBatchResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_gometheus_proto_init() }
func file_gometheus_proto_init() {
	if File_gometheus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gometheus_proto_rawDesc), len(file_gometheus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gometheus_proto_goTypes,
		DependencyIndexes: file_gometheus_proto_depIdxs,
		MessageInfos:      file_gometheus_proto_msgTypes,
	}.Build()
	File_gometheus_proto = out.File
	file_gometheus_proto_goTypes = nil
	file_gometheus_proto_depIdxs = nil
}
